ref(build): Introduce central `build` directory to packages with bundles (#4838)
Adds the central build directory to all our packages producing CDN bundles in addition to NPM tarballs:
- Browser
- Integrations
- Tracing
- WASM

Additionally, the script that would formerly be called `postbuild.ts` is now `prepack.ts` and it runs first when executing `yarn build:npm`, followed by the tarball packing procedure via npm. 
Exception: Tracing needs to have the modified package.json in the build dir for our Playwright integration tests, so `prepack.ts` is also executed after every build.