test(node): Ensure logs are auto-printed when a test fails (#21887)
We can opt-in to show sub process logs in node-integration-tests with
`DEBUG=1`. This PR adjusts this so that we automatically show logs when
a test fails. For example, in addition to this:

```
 FAIL  suites/express/tracing/test.ts > express tracing > should create and send transactions for Express routes and spans for middlewares. xxxx [esm]
 FAIL  suites/express/tracing/test.ts > express tracing > should create and send transactions for Express routes and spans for middlewares. xxxx [cjs]
Error: Timed out waiting for server port
 ❯ waitFor utils/runner/createRunner.ts:648:13
    646|     remaining -= 100;
    647|     if (remaining < 0) {
    648|       throw new Error(message);
       |             ^
    649|     }
    650|   }
 ❯ Object.makeRequest utils/runner/createRunner.ts:533:13
```


You may see:

```
stdout | suites/express/tracing/test.ts > express tracing > should create and send transactions for Express routes and spans for middlewares. xxxx [esm]

--- Captured child process output for /Users/francesco/git/sentry-javascript-2/dev-packages/node-integration-tests/suites/express/tracing/tmp_mr21unou_f00oan/scenario.mjs ---
file:///Users/francesco/git/sentry-javascript-2/dev-packages/node-integration-tests/suites/express/tracing/tmp_mr21unou_f00oan/instrument.mjs:5
Sentry.blasdabs();
       ^

TypeError: Sentry.blasdabs is not a function
    at file:///Users/francesco/git/sentry-javascript-2/dev-packages/node-integration-tests/suites/express/tracing/tmp_mr21unou_f00oan/instrument.mjs:5:8
    at ModuleJob.run (node:internal/modules/esm/module_job:325:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:606:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:112:9)

Node.js v20.19.5
--- End of captured child process output ---
```

Which should hopefully make it easier to figure out some test failures
etc.