test(hono): Fix hono e2e tests (#18000)
ATM there are failing Hono E2E tests (e.g.
[here](https://github.com/getsentry/sentry-javascript/actions/runs/18714106732/job/53370082672?pr=17998)),
which print out following:

```sh
Error: src/index.ts(20,3): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
```

The reason was, that the types were not there yet. I just wonder why it
was working before. In follow up PRs I will try to update Cloudflare
tests with its integrations.