fix(node): Revert to dynamic `require` call to fix monkey patching (#7430)
Partially revert #7377 which caused monkey patching errors when patching the native `http` and `https` modules in the Node SDK (#7425). Similarly, also our Serverless SDK was subjected to the same problem (#7421). 

The problem is that `import` doesn't permit monkey patching of the imported (`http(s)`) module, producing this error:

```bash
TypeError: Cannot assign to read only property 'get' of object '[object Module]'
```

I tried using a dynamic import instead but got the same result. So it seems like we can only use `require` here :(