Try aliasing preact typescript declaration to fix ts errors (#11088)
Right now the feedback PR fails ts3.8 e2e tests. This is because of TS issues, preact types do not work well with older
TS types:

```
> @sentry-internal/ts3.8-test@ type-check /home/runner/work/sentry-javascript/sentry-javascript/dev-packages/e2e-tests/test-applications/generic-ts3.8
> tsc --project tsconfig.json

##[debug]Dropping file value '/home/runner/work/sentry-javascript/sentry-javascript/node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts'. Path does not exist
Error: node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts(1462,3): error TS2304: Cannot find name 'SubmitEvent'.
##[debug]Dropping file value '/home/runner/work/sentry-javascript/sentry-javascript/node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts'. Path does not exist
Error: node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts(1479,25): error TS2304: Cannot find name 'PictureInPictureEvent'.
##[debug]Dropping file value '/home/runner/work/sentry-javascript/sentry-javascript/node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts'. Path does not exist
Error: node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts(2549,65): error TS2304: Cannot find name 'MathMLElement'.
##[debug]Dropping file value '/home/runner/work/sentry-javascript/sentry-javascript/node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts'. Path does not exist
Error: node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts(2565,49): error TS2304: Cannot find name 'MathMLElement'.
##[debug]Dropping file value '/home/runner/work/sentry-javascript/sentry-javascript/node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts'. Path does not exist
Error: node_modules/.pnpm/registry.npmjs.org+preact@10.19.6/node_modules/preact/src/jsx.d.ts(2571,52): error TS2304: Cannot find name 'MathMLElement'.
```

Essentially these types don't work on older versions and because the
feedback package is depended on by the browser package, we will break a
certain set of our users. We have to fix this before we can ship because
of the browser package dependency.

To get around this, we do a workaround with
`packages/feedback/scripts/shim-preact-export.js`. Essentially we shim
the preact type in our exports, which should change what the declaration
files themselves point to. So something like the following:

```ts
import type { ComponentChildren, VNode } from 'preact';
```

turns into

```ts
// no preact to be seen!
type ComponentChildren: any;
type VNode: any;
```