feat(browser): Add detail to measure spans and add regression tests (#16557)
resolves https://github.com/getsentry/sentry-javascript/issues/16237

In #16348 we had to revert the PR that added `detail` to `measure` spans
as attributes.

measure API:
https://developer.mozilla.org/en-US/docs/Web/API/Performance/measure
detail:
https://developer.mozilla.org/en-US/docs/Web/API/PerformanceMeasure/detail

This was
[reverted](https://github.com/getsentry/sentry-javascript/issues/16347)
because it was causing issues in firefox, specifically this error was
being thrown

```
Error: Permission denied to access object
  at _addMeasureSpans(../../node_modules/@sentry-internal/browser-utils/build/esm/metrics/browserMetrics.js:255:41)
  at X2e/<(../../node_modules/@sentry-internal/browser-utils/build/esm/metrics/browserMetrics.js:194:9)
  at addPerformanceEntries(../../node_modules/@sentry-internal/browser-utils/build/esm/metrics/browserMetrics.js:174:48)
  at idleSpan.beforeSpanEnd(../../node_modules/@sentry/browser/build/npm/esm/tracing/browserTracingIntegration.js:90:9)
  at span.endapply(../../node_modules/@sentry/browser/node_modules/@sentry/core/build/esm/tracing/idleSpan.js:52:9)
  at Coe/<(../../node_modules/@sentry/browser/node_modules/@sentry/core/build/esm/tracing/idleSpan.js:196:12)
  at sentryWrapped(../../node_modules/@sentry/browser/build/npm/esm/helpers.js:38:17)
```

From debugging, this seems to be coming from a `DOMException` being
thrown @https://developer.mozilla.org/en-US/docs/Web/API/DOMException

This was re-implemented, and then we added tests to validate that this
wouldn't break on firefox.

---------

Co-authored-by: Cursor Agent <cursoragent@cursor.com>