feat(react): Add `Sentry.reactErrorHandler` (#12147)
This PR introduces `Sentry.reactErrorHandler`, which looks like so:

```js
import * as Sentry from '@sentry/react';
import { hydrateRoot } from "react-dom/client";

ReactDOM.hydrateRoot(
  document.getElementById("root"),
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  {
    onUncaughtError: Sentry.reactErrorHandler(),
    onCaughtError: Sentry.reactErrorHandler((error, errorInfo) => {
      // optional callback if users want custom config.
    }),
  }
);
```

To validate this change, we add a react 19 e2e test.